server:
  port: 9090

eureka:
  instance:
    hostname: localhost
  #    preferIpAddress: true
  client:
#    registerWithEureka: false #设置为false表示不向注册中心注册自己
    fetchRegistry: false #注册中心，不需要检索服务，所以设置为false
    serviceUrl:
      defaultZone: http://127.0.0.1:1112/eureka/, http://192.168.2.216:1111/eureka/

spring:
  application:
    name: sub-provider