server:
  port: 1110

eureka:
  instance:
    hostname: localhost
#    preferIpAddress: true
  client:
#    register-with-eureka: false #设置为false表示不向注册中心注册自己
#    fetch-registry: false #注册中心，不需要检索服务，所以设置为false
#    registerWithEureka: false
#    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
