server:
  port: 1112

spring:
  application:
    name: eureka-server
  profiles:
    active: peer2
eureka:
  instance:
    hostname: 127.0.0.1
#    preferIpAddress: true
  client:
#    registerWithEureka: true
#    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.2.216:1111/eureka/
#      defaultZone: http://peer1:1111/eureka/